### PR TITLE
Online Stuff

### PR DESCRIPTION
**Pull request by nico-abram**
To show a second set of scores/judgements/grade/options on EvaluationScreen only when playing online which update when you scroll through players i added [ScreenNetEvaluation] in metrics and a bunch of grade stuff on /Graphics(took these from ultralight i think).

Reduced Chatbox output font and increased lines(in metrics) and accordingly edited the square/quad which is the background of the chatbox in _chatbox.lua in /BGAnimations. It was kinda ridicolously big and you only had 10 lines to read.

Added overlays with the usual player stats, etc in selectroom and netselectmusic.

Added a bunch of stuff on NetSelectMusic decorations(Mina diff display, bpm display, taps/jumps/etc display, cd title display, PB score, etc)
Fixed NetSelectMusic underlay which didn't show the background image.
Added an independant search bar in NetSelectMusic(This is just provisional until the actual searchbar gets in here, if it ever does, but it's pretty nice in the mean time)

Most of these things were done by Alamanar(He grabbed some stuff from misterkister) and i took some things from ultralight.

### CODE REVIEW

**Comment by MinaciousGrace** [comment]
looks good, i'll try to get this merged before 0.53 release

what's stopping me from doing it immediately is I'd like to modify the search code to use the internal music wheel search functions that were added, which allow for dynamic search result updates

edit: pulled to test stuff and got errors with multiple theme element conflicts (screenetselectmusic decorations) among others, these need to be fixed before i can merge

**Comment by nico-abram** [comment]
I'm very sorry about that, forgot to remove a couple files and there was a conflict with multiple files for one screen. Fixed that.

**Comment by nico-abram** [comment]
Fixed some problems there were with colors. 
Combo didnt have a 'TapNoteScore_Combo' so i just asssigned 'TapNoteScore_W2' which is yellow  and since the function getSongLengthColor is no longer present in color_config i removed the length label recolouring so it's always white.

**Comment by nico-abram** [comment]
I edited the searchbar to use the internal search system(It uses a button on the top overlay quad because when i tried doing a tab quad with 'Search' on top of the bottom one it ended up a bit on top of the chatbox). I added it(the searchbar) to the 'ScreenNetSelectBase overlay' and deleted 'ScreenNetSelectMusic overlay'(I think these 2 screens were conflicting).
There are probably better ways to do this, but for the moment this seems to work.
Since i can't(I dont know how) hide the chatbox text i added a quad background to the search actor.

**Comment by nico-abram** [comment]
First i changed the search input method for online to ScreenTextEntry because the input function and the chatbox input were conflicting(when you typed something to search it also gets typed in the chatbox).

Secondly I just realized using wife searching online results in a crash if someone starts a song while youre searching and the song isn't in your search results and you're on a pack. If you're on a song you start playing the song you had selected(regardless of what song was actually picked). If you play another song the SMO server will think you played the right song(In your profile the song's name will be the one that was picked).

I'm attaching crashinfo here. For the moment it's probably best to leave it with the secondary search function(This one doesn't change the wheel options, instead it moves you to the results). It might not be as pretty but it isnt crashing.
[crashinfo.txt](https://github.com/xwidghet/stepmania/files/670199/crashinfo.txt)

I don't actually have any idea how the musicwheel works or how to fix this(I'm guesssing making the musicwheel reload without search activated whenever SM recieves a song select from SMO before doing anything would fix it but i dont know)

EDIT: I've been looking at code and i think that adding something like 'm_MusicWheel->ReloadSongList(false, "");' to 'void ScreenNetSelectMusic::HandleScreenMessage' in '/src/ScreenNetSelectMusic.cpp' before 'Song* CurSong = m_MusicWheel.GetSelectedSong();' might fix this but i'm not sure at all.(Preferably inside an if checking if there is or not a search active at the moment, but i don't know if you have a variable or method inside the music wheel object to check this)

**Pull request merged**
